[package]
name = "chip-eight"
version = "0.1.1"
edition = "2024"
description = "A chip 8 interpreter/emulator with no display or input implemented. Input and display are instead provided by traits for the user to implement on any input or display device"
license = "MIT"

[dependencies]

[dev-dependencies]
winit = "0.30.13"
softbuffer = "0.4.8"
